{% set name = "inspectds" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inspectds-{{ version }}.tar.gz
  sha256: f300b89d02bb7e628b14df9bbea5b7e57f838b32cc0a5c30e9a2b172f65a5e5d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - inspectds = inspectds.cli:app
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9
    - netcdf4
    - typer
    - xarray
    - xarray_selafin
    - zarr >=2.8
    - cfgrib >=0.9

test:
  imports:
    - inspectds
  commands:
    - pip check
    - inspectds --version
    - inspectds --help
  requires:
    - pip

about:
  home: https://github.com/pmav99/inspectds.git
  summary: 'A CLI utility to print metadata of datasets in various formats (e.g. NetCDF, zarr, GRIB, Selafin etc)'
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmav99
    - tomsail
