{% set name = "inspectds" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inspectds-{{ version }}.tar.gz
  sha256: ff2a06d86222887eed8611bd02077d696cb4d4028893c76540b4373b6e719d76

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - inspectds = "inspectds.cli:app"
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9
    - netcdf4
    - typer
    - xarray
    - xarray_selafin
    - zarr >=2.8
    - cfgrib >=0.9

test:
  imports:
    - inspectds
  commands:
    - pip check
    - inspectds --version
    - inspectds --help
  requires:
    - pip

about:
  home: https://github.com/pmav99/inspectds.git
  summary: 'A CLI utility to print metadata of datasets in various formats (e.g. NetCDF, zarr, GRIB, Selafin etc)'
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmav99
    - tomsail
