{% set name = "inspectds" %}
{% set version = "0.5.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/inspectds-{{ version }}.tar.gz
  sha256: a17f07fa1ea8c99de342282275bae30d8680315f1631f4d7c1d19b7a5a9b6123

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - inspectds = inspectds.cli:app
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - netcdf4
    - rioxarray
    - typer >=0.12.0
    - xarray
    - xarray_selafin
    - zarr >=2.8
    - cfgrib >=0.9

test:
  imports:
    - inspectds
  commands:
    - pip check
    - inspectds --version
    - inspectds --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pmav99/inspectds.git
  summary: 'A CLI utility to print metadata of datasets in various formats (e.g. NetCDF, zarr, GRIB, Selafin etc)'
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmav99
    - tomsail
