{% set name = "inspectds" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inspectds-{{ version }}.tar.gz
  sha256: 926b33bacf40b0b5a5d3905b5777f21f0dc2a71032e6f1bcacad079127e9e6f3

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - inspectds = "inspectds.cli:app"
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.9
    - xarray
    - zarr >=2.8
    - typer
    - netcdf4
  run_constrained:
    - cfgrib >=0.9

test:
  imports:
    - inspectds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pmav99/inspectds.git
  summary: 'A CLI utility to print metadata of datasets in various formats (e.g. NetCDF, zarr, GRIB etc)'
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmav99
